
version: "3.8"
services:
  db:
    container_name: psql-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      #POSTGRES_PASSWORD: root12345
      POSTGRES_DB: test_db
      #POSTGRES_DB_PASSWORD_FILE: /run/secrets/db_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/db_secret
      #Not Working

    secrets:
      - db_secret
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_secret
      #PGADMIN_DEFAULT_PASSWORD: root1234
    secrets:
      - pgadmin_secret
    ports:
      - "5050:80"
  
secrets:
  db_secret:
    file: secrets/db
  pgadmin_secret:
    file: secrets/pgadmin
